services:
  - type: web
    name: testero-backend
    runtime: java
    plan: free
    region: frankfurt
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -Xmx256m -XX:+UseSerialGC -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
