-- ============================================================
-- Testero — Dev seed data (DISABLED)
--
-- This file previously contained sample data (teachers, students,
-- classes, tests with questions and options) useful for first-time
-- contributors to explore the application locally.
--
-- Production seed data is now managed separately via:
--   docs/db_seed/seed-local.sh  (users + classes for local dev)
--   docs/db_seed/seed-prod.sh   (full data for Supabase production)
--
-- To populate your local database after starting Spring Boot, run:
--   ./docs/db_seed/seed-local.sh
--
-- This file is intentionally empty so that Liquibase marks the
-- changeset as executed without inserting any data.
-- ============================================================
